package de.tu_darmstadt.gdi1.framework.exceptions;

/**
 * will be thrown if a next level should be loaded and in the current directory do not exists a next level.
 * 
 * @author jonas
 *
 */
public class NoNextLevelException extends Exception {

	/**
	 * generated by java.
	 */
	private static final long serialVersionUID = -8444398086220492991L;

}
